version: "3.8"

services:
  fanfuryd:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/fanfury/localterra:0.2.0
    hostname: fanfuryd
    pull_policy: always
    volumes:
      - terra:/app
    networks:
      - default
    ports:
      - "1317:1317"
      - "8080:8080"
      - "9090:9090"
      - "9091:9091"
      - "26657:26657"

volumes:
  terra:

networks:
  default:
